### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by jerryyang0611** [mr-pennyworth/alfred-better-dictionaries#1]
Thanks for this fantastic workflow. However, after setting up the workflow and granting the permission, I still can't manage to get the preview window to pop up.  Do this feature only support the New Oxford American Dictionary? 

Bad news, I've accidentally imported the workflow to Alfred again which updated and reset the workflow script from scratch. 
However, I've already imported the New Oxford American Dictionary and 牛津英汉汉英词典 before, when I wanted to import this dictionary again, it's now showing up in the options, meaning that I cannot get the old workflow you created for us while importing those dictionaries.  

![image](https://user-images.githubusercontent.com/45359868/113474547-2833de00-94a3-11eb-8cbc-fd35a7dfd181.png)

Now I only got this new imported script but cannot find the preview installed dict (New Oxford American Dictionary and 牛津英汉汉英词典) b4... 

![image](https://user-images.githubusercontent.com/45359868/113474626-9aa4be00-94a3-11eb-842d-5b240d048c25.png)

Is there any options for running / importing those installed dictionaries into the workflow? Thanks in advance.

**Comment by mr-pennyworth** [comment]
Apologies! This workflow is way too complicated, and I'm working on a revamp which should fix most issues around reliability, resetting etc. However, at present, my day job has gotten very hectic and am not able to spend time on the revamp :(

**Comment by mr-pennyworth** [comment]
Hi @jerryyang0611, I'm unable to understand the bug report.
1. What dictionaries are available on your machine?
2. Which of them are not showing up in the workflow for importing?
3. For the ones that aren't showing up, do you know which folder they are installed in?

**Comment by jerryyang0611** [comment]
So I've installed and updated the latest workflow just now, and it updated all of my settings but also clean out all my previously imported dictionary. I think it's because I've previously installed the dictionary, when I type `.dict-import` now, only the ones that are not installed on my laptop yet will be showing. So right now, what I have got in the options is only this:
![image](https://user-images.githubusercontent.com/45359868/121203104-c199ba80-c86d-11eb-8f02-2ef0c79e8a5a.png)
What I mean is, whenever I updated the workflow or installed the new version of the workflow, the old setting and workflow script that has been created before will be flushed and disappear. And when I try to import those "already-installed" dictionary using `.dict-import`, there are no such options. 

Therefore, can you tell me how to create the workflow as you did for us using `.dict-import`? or could you tell me where are those installed dictionary located in which folder? (it would be better for you to teach me how to link and create those script to reach the same effect as via `.dict-import`. 

Thanks so much for the help, and I'm looking forward to getting the support. 
Jerry

**Comment by jerryyang0611** [comment]
Or maybe it's good to have something like `.clear-imported-dictionary` options for us to **totally remove** the installed and imported dictionary on our computer. By doing this, the next time when we do the ".dict-import`, the options will show up again, and users like me don't have to manually create the workflow like I am going to do. Hope you understand. 

But thanks again for creating such an amazing workflow. :) looking forward to the new update or the solutions.

**Comment by jerryyang0611** [comment]
When I do `lookup`, my current installed dictionary in the Better-dict.app includes: 

![image](https://user-images.githubusercontent.com/45359868/121207275-11c64c00-c871-11eb-8918-7382cfe4ed15.png)

these are all the dictionaries that I've installed on my laptop, but I'm now struggled to create the workflow as you do for me using `.dict-import` in the editor.

**Comment by mr-pennyworth** [comment]
@jerryyang0611 I updated the workflow to add a `.dict-factory-reset` keyword.
I tried it and it seems to work. Can you try it too and let me know if it works?
Note: you will have to run `.setup-better-dictionaries` again after installing the updated workflow

**Comment by jerryyang0611** [comment]
Thanks so much for this fast update and response. It works okay at the moment :) 
Absolutely love your amazing workflow!
