### ISSUE TITLE
Just getting Better Dict on startup (when I try to import first dictionary)

### ISSUE THREAD

**Issue by chessemuffin** [mr-pennyworth/alfred-better-dictionaries#10]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/89578599/138430430-e9a9705d-4593-4924-8b9e-1d2ec92cd626.png">
 
and I've allowed permissions
<img width="611" alt="image" src="https://user-images.githubusercontent.com/89578599/138430567-fe4f41a6-3b32-480c-b1ed-d81e57f4fde7.png">

**Comment by MrModest** [comment]
Same for me also

**Comment by Rifatmahmood** [comment]
Same for me.

**Comment by mr-pennyworth** [comment]
This should be fixed in the latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.5
(Tested on Intel Mac only, help in testing on Apple Silicon greatly appreciated 😇)
