### ISSUE TITLE
[BUG] it doesn't work with Alfred Modern theme

### ISSUE THREAD

**Issue by aiPenguin** [mr-pennyworth/alfred-better-dictionaries#11]
Hi, I really like this extension, thanks a lot for your work. 
The extension works well with most themes, but when I use _Alfred Modern (Dark)_ theme it just doesn't show any search result.

<img width="1174" alt="CleanShot 2021-12-19 at 23 38 52@2x" src="https://user-images.githubusercontent.com/46262493/146694447-75dace06-a882-4bea-ba92-5a07e41ab2a0.png">
with default theme, it works well.

<img width="1177" alt="CleanShot 2021-12-19 at 23 39 34@2x" src="https://user-images.githubusercontent.com/46262493/146694448-6843456e-b238-44e7-a897-73cce4fc2b85.png">
with _Alfred Modern (Dark)_ theme, it shows no result.

Best regards

**Comment by sophlzy3** [comment]
same problem but now it doesn't work with any theme, even the duplicated ones

**Comment by tientaidev** [comment]
Same problem. It did not work with Alfred Modern theme.

**Comment by mr-pennyworth** [comment]
Thanks for the bug report @aiPenguin, @sophlzy3, and @tientaidev!
This issue is fixed in the latest release.
The pane doesn't look as good as it does with other themes, but now the pane doe show up 😇
