### ISSUE TITLE
"After importing the workflow" .... 

### ISSUE THREAD

**Issue by benjaminhoffman** [mr-pennyworth/alfred-better-dictionaries#13]
Clearly I am missing something obvious because the README says _"After importing the workflow"_ but after cloning this lib, I don't see any `.alfredworkflow.` file.  

How do I import this workflow?

**Comment by ChrisBarfod** [comment]
Download the workflow file from the top of the readme. It's the 'download' button underneath the icon. Once downloaded, double click the file and it should import into Alfred.

**Comment by benjaminhoffman** [comment]
ah yes, the small `download` button did the trick! thx @ChrisBarfod ...
but now strangely, even after granting permission and restarting alfred, it's still telling me to update my a11y perms.  I'm going to continue to play with it but would love if there were more explicit install instructions.
thanks pennyworth for creating this!
![Screen Shot 2022-01-29 at 13 31 17](https://user-images.githubusercontent.com/6520022/151675008-3b04998b-beae-4ca8-8764-39c931511794.png)
![Screen Shot 2022-01-29 at 13 31 23](https://user-images.githubusercontent.com/6520022/151675009-4621a204-cc9d-4a40-a727-b6c5aed7c5a9.png)

**Comment by benjaminhoffman** [comment]
still having an issue but i just noticed this is the same as https://github.com/mr-pennyworth/alfred-better-dictionaries/issues/15 and https://github.com/mr-pennyworth/alfred-better-dictionaries/issues/8
