### ISSUE TITLE
No longer works in macOS 12.3

### ISSUE THREAD

**Issue by notDavid** [mr-pennyworth/alfred-better-dictionaries#15]
Fyi, Apple removed python 2 in the latest macOS 12.3 update:

https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes

> Python Deprecations
> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

Which results in:
```
❯ ./search.sh "hello" "com-apple-dictionary-NOAD"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5146  100  5118  100    28   220k   1232 --:--:-- --:--:-- --:--:--  314k
./search.sh: AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane: /usr/bin/python: bad interpreter: No such file or directory
```

**Comment by dchew006** [comment]
same issue. Reinstalling python 2 under the Homebrew prefix doesn't seem to solve the issue.

**Comment by lelguo** [comment]
Same issue here with macOS 12.3

**Comment by meinspitzname** [comment]
Same here

**Comment by notDavid** [comment]
For anyone looking for a workaround, this fixes it for me:

- install python2, see https://www.alfredapp.com/help/kb/python-2-monterey/  (and https://www.alfredapp.com/blog/guides-and-tutorials/python-2-workflows-on-macos-monterey-12-3/ )
- add `export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` as first line to all your `Search ...` Script Filters in the workflow
- In:
	`.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred.py"`
	and
	`.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane"`
	add this as first line to use python2 instead of python3 : `#!/usr/bin/env python`

**Comment by meinspitzname** [comment]
@notDavid How do you do the last step? I can't edit the exec file

> .../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane"
add this as first line to use python2 instead of python3 : #!/usr/bin/env python

For now, I get an error.

**Comment by notDavid** [comment]
@meinspitzname `.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane` is just a text file, you can drag it into any text editor.

**Comment by meinspitzname** [comment]
Thanks @notDavid. Should I also delete the first line that was there before?
<img width="493" alt="image" src="https://user-images.githubusercontent.com/49695717/161056251-5fd1eed7-1470-4740-8f06-845dbe7ef7bb.png">

**Comment by notDavid** [comment]
@meinspitzname Yes :-)

**Comment by meinspitzname** [comment]
@notDavid  It somehow still gives me this error: <img width="297" alt="image" src="https://user-images.githubusercontent.com/49695717/161056598-eb3e1b78-f7d3-4fbd-86c5-a4c14a508334.png">

**Comment by meinspitzname** [comment]
@notDavid Can I add `export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` simply as is or do I need to substitute {PATH} with something?

**Comment by notDavid** [comment]
@meinspitzname Well, if you click the blue `Script Filter` text in your screenshot above, it will select the action/script in the workflow that triggers the error.

You should repeat step 2 in my above post for every dictionary(= script filter) that you have added.

> Can I add export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}" simply as is...

Yes, as it is.

**Comment by meinspitzname** [comment]
@notDavid I've already added the code there:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/49695717/161058888-e36f8c70-fbbf-4c8a-b3d8-5e4dfea52f1d.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/49695717/161058879-4677de69-391c-42f1-8568-0a1e325460a9.png">

**Comment by notDavid** [comment]
@meinspitzname I remember seeing that error once, i just clicked 'Terminate' and it resumed and everything worked fine.
Perhaps it also depends on the dictionary, maybe try importing another dictionary to see if that works.

Perhaps it's related to [this bug](https://github.com/mr-pennyworth/alfred-better-dictionaries/issues/8), i don't know.

You can also try my workflow with my changes, perhaps that helps. I've uploaded it here https://github.com/notDavid/alfred-better-dictionaries-tmp 
You probably have to remove my imported dictionaries or change some keywords/keybindings...

**Comment by benjaminhoffman** [comment]
im facing the same issue but im still v12.1.  im excited to get this working

**Comment by kenanmike** [comment]
To give more info, the built in Alfred dictionary still works but not this workflow:

https://user-images.githubusercontent.com/85374001/162736082-791b8679-81bb-45d6-874f-fe675fbc5668.mov

**Comment by notDavid** [comment]
This workflow is no longer working properly, starting with macOS 12.3.
So, there is no added value for everyone to confirm that it's not working for them too :-)

Hopefully the Developer, or someone else, will update this workflow to Python3 at some point. Until then, it is broken.

I have shared a temporary workaround in my comment above that works for me, and may or may not also work for you...

Hope that helps.

**Comment by kenanmike** [comment]
> This workflow is no longer working properly, starting with macOS 12.3. So, there is no added value for everyone to confirm that it's not working for them too :-)
> 
> Hopefully the Developer, or someone else, will update this workflow to Python3 at some point. Until then, it is broken.
> 
> I have shared a temporary workaround in my comment above that works for me, and may or may not also work for you...
> 
> Hope that helps.

I just factory reset the dictionaries, re-installed the workflow, and added the 1 line of script you mentioned and it's now all working. Thanks so much again for the workaround!

**Comment by BitcoinLixin** [comment]
> For anyone looking for a workaround, this fixes it for me:
> 
> 1. install python2, see https://www.alfredapp.com/help/kb/python-2-monterey/  (and https://www.alfredapp.com/blog/guides-and-tutorials/python-2-workflows-on-macos-monterey-12-3/ )
> 2. add `export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` as first line to all your `Search ...` Script Filters in the workflow
> 3. In:
>    `.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred.py"`
>    and
>    `.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane"`
>    add this as first line to use python2 instead of python3 : `#!/usr/bin/env python`

It works! Thanks so much!

For those who are less tech-savvy. Here is some extended guidance with screenshots - 

>  2. add `export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` as first line to all your `Search ...` Script Filters in the workflow

In this step, you need add `export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` to the dictionaries' scripts.
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/8241577/163669196-e50fa23f-f1c1-4344-839a-352c3d6591da.png">

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/8241577/163669210-6ae28848-6d84-464f-95f6-785b75b7524f.png">

> 3. In:
>    `.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred.py"`
>    and
>    `.../workflows/user.workflow.AD8AD798-4133-46AE-8668-A65FC514A03B/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane"`
>    add this as first line to use python2 instead of python3 : `#!/usr/bin/env python`

To find the file you need to modify, follow these steps:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/8241577/163669268-27e86475-4b97-46de-b62f-144142555457.png">

<img width="991" alt="image" src="https://user-images.githubusercontent.com/8241577/163669296-31b41f43-1755-4fbb-a2c8-533ef7279317.png">

Then go to `Contents` - `Resources` - `scripts`

Then open `alfred-extra-pane` and `alfred.py` with TextEdit.app, add `#!/usr/bin/env python` at the top.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/8241577/163669371-cd82342a-589e-4c0b-98ff-df6df0425391.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/8241577/163669392-f935a50c-0309-4a74-a0c2-537e8c213426.png">

Note:
* If you encounter any error popups saying "Open Console" or "Terminate", just tap "Open Console" and repeat the step again.
* In the whole process you may need to go to 'System Preference - Security & Privacy - General' and 'System Preference - Security & Privacy - Privacy - Accessibility` for authorization several times.

**Comment by chence08** [comment]
Can confirm the workaround is valid on macOS 12.3.1
<img width="943" alt="Screenshot 2022-05-01 at 08 54 47" src="https://user-images.githubusercontent.com/65040076/166127608-ec2aa22d-5e87-404d-b1fe-14ae537afc0f.png">

**Comment by Sekibutsu** [comment]
Thanks so much for this. Also wanted to confirm that the workaround works flawlessly, and thanks to @BitcoinLixin 's clear instructions it was a breeze to implement even with zero tech capabilities.

**Comment by jcokc** [comment]
I just did this workaround, which is not working on Mac Sonoma Version 14.0 (23A344). When typing a query into the dictionary, no search results... 
<img width="757" alt="Screenshot 2023-10-30 at 9 25 36 PM" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/149344688/9c8cd333-2149-4a3a-b26a-f683d7c70cf3">

**Comment by mr-pennyworth** [comment]
I don't have access to Apple Silicon mac, so can't confirm whether the workflow works on it.
For Intel macs, I can confirm that the latest build works on macOS 14.3.

I wasn't able to make it compatible with the previous version though.
If you'd be interested in trying it out, I'd recommend deleting the old version first.

**Comment by mr-pennyworth** [comment]
This should be fixed in the latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.5
(Tested on Intel Mac only)
