### ISSUE TITLE
Font size increase? It uses JXA.

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-better-dictionaries#17]
Under "def search_field_height()" what variable can we tamper with to see font size changes. 

The font change is doable, but the size is a bit tricky. If anyone has come across it.

Not familiar with JXA, so if anyone has any ideas, let's experiment :)
The following is in the python script of this workflow. I think that's the area to increase the dictionary result sizes. 

```
return int(execJXA('''
    function run(argv) {
      var system = Application('System Events');
      var alfred = system.processes['Alfred'];
      return alfred.windows[0].textFields[0].size.get()[1];
    }'''))


@cached
def result_height():
  th = theme()
  return (th['result.paddingVertical'] * 2
          + th['separator.thickness']
          + max(th['result.iconSize'],
                (th['result.text.size']
                 + th['result.textSpacing']
                 + th['result.subtext.size'])))
```

**Comment by yarub123** [comment]
@mr-pennyworth 👀 😅

**Comment by mr-pennyworth** [comment]
See #19
