### ISSUE TITLE
Any way to add dictionaries we have downloaded?

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-better-dictionaries#18]
Like the Hunspell English one?

**Comment by mr-pennyworth** [comment]
@yarub123 this workflow only works with dictionaries that come in the `.dictionary` format.
(which, I assume, means only the ones you can enable using `Dictionary > Settings...`)
<img width="588" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/74945464/16c4a51f-f8c1-4a5a-91af-29f013264fca">
