### ISSUE TITLE
[BUG] AlfredExtraPane doesn't work properly

### ISSUE THREAD

**Issue by twio142** [mr-pennyworth/alfred-better-dictionaries#2]
![2021-05-04-222316](https://user-images.githubusercontent.com/64556708/117065790-31c19780-ad28-11eb-8931-73dc85d11bc0.gif)

The AlfredExtraPane pops up shortly after search completed and then just disappears.
Also, its position is not matching the Alfred window, and the css style is dimmed.

Moreover, I'd wish the output of the workflow to be the look up result, instead of a html file path.

P.S. Thanks for the development! :)

**Comment by mr-pennyworth** [comment]
Apologies! This workflow is way too complicated, and I'm working on a revamp which should fix most issues around reliability, resetting, extra pane positioning etc. However, at present, my day job has gotten very hectic and am not able to spend time on the revamp :(

**Comment by jerryyang0611** [comment]
I've encountered this problem b4, you can try to kill/quit Alfred and reopen it, and I think it should be working fine  
Hope this will help. :) if it's not, do it again. It should be okay.

**Comment by mr-pennyworth** [comment]
This should be fixed in the latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.6
(Tested on Intel Mac only, help in testing on Apple Silicon greatly appreciated 😇)
 
I have simplified `AlfredExtraPane`, and fixed the positioning issues.
