### ISSUE TITLE
If I attempt to remove it later, would the storage (near 1GB, which this takes), be cleared on it's own?

### ISSUE THREAD

**Issue by neilpat05** [mr-pennyworth/alfred-better-dictionaries#20]
For me, space is a huge thing, and I might need to remove this depending on my work month. But I do need this often, so if I need to remove it, would the storage it uses be cleared easily?

**Comment by mr-pennyworth** [comment]
yup, @neilpat05 entering `.dict-factory-reset` will purge all the data and indexes and give back the space.
