### ISSUE TITLE
In-Alfred live previews not working 

### ISSUE THREAD

**Issue by jamalabd** [mr-pennyworth/alfred-better-dictionaries#21]
In-Alfred live previews aren't working for me. 

Not sure why, followed `.setup-better-dictionaries` as welll

<img width="688" alt="Screenshot 2023-12-13 at 12 44 48 PM" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/45414121/e109245e-d591-449b-a998-0ba9522977b2">

**Comment by mr-pennyworth** [comment]
This should be fixed in the latest release: https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.5
(Tested on Intel Mac only)

**Comment by jamalabd** [comment]
I see, I'm running M1 Mac.
