### ISSUE TITLE
Error Importing Dictionary - Littre

### ISSUE THREAD

**Issue by makzsslm** [mr-pennyworth/alfred-better-dictionaries#29]
I get an error while importing the following french dictionary:

`Littré`

```
ERROR: Better Dictionaries[Run Script] Traceback (most recent call last):
  File "BetterDict.py", line 451, in <module>
  File "BetterDict.py", line 335, in import_dict
  File "BetterDict.py", line 48, in get_word_defs_map
zlib.error: Error -3 while decompressing data: incorrect header check
[38500] Failed to execute script 'BetterDict' due to unhandled exception!
```

This might be a bit of an edge case, it's not an included dict, I got it from [an ancient website](https://www.competencemac.com/Bureautique-Dictionnaires-en-francais_a1737.html)

Still posting the issue because I found [this stackoverflow issue](https://stackoverflow.com/questions/3122145/zlib-error-error-3-while-decompressing-incorrect-header-check) that describes a simple solution that might be worth trying.

**Comment by mr-pennyworth** [comment]
Thanks for the report @makzsslm!
Fixed it in the latest build! :)
