### ISSUE TITLE
different search results from alfred default dictionary

### ISSUE THREAD

**Issue by snam24** [mr-pennyworth/alfred-better-dictionaries#3]
Hi, thanks so much for developing the workflow.

I found that **search results** are a little bit different from the default one. Can you please add the feature in the revamped version that matches the search result from the alfred default dictionary?

e.g., Alfred default search result for 'lice'
https://www.dropbox.com/s/b12sjbntd7fu1yx/Screenshot_2021-05-18-11_42_02_ZPIM2Y.png?dl=0

cf., BetterDict search result for 'lice'
 https://www.dropbox.com/s/le9q68fmn0l5700/Screenshot_2021-05-18-11_43_25_KVzO78.png?dl=0

**Comment by mr-pennyworth** [comment]
@snam24 thanks for the report!
Interesting bug!

**Comment by mr-pennyworth** [comment]
### Built-in:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/74945464/121070712-ad61a900-c7ec-11eb-8335-51fe62825718.png">

### BetterDict:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/74945464/121070642-97ec7f00-c7ec-11eb-8ed4-1098e3b39aeb.png">
