### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by makzsslm** [mr-pennyworth/alfred-better-dictionaries#31]
It seems after this recent change:

```Instead of needing to run `.setup-better-dictionaries`,
now we run `./setup.sh` before each dict import.```

the script is no working properly.

On a fresh install (see previous issue) i get this error:

<img width="268" alt="image" src="https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/125161526/d19de225-0a12-48bb-a1c1-767e26d3478d">

**Comment by makzsslm** [comment]
*When running the script manually from the terminal, it does work

**Comment by mr-pennyworth** [comment]
Whoops! Thanks for the report @makzsslm!
I've fixed it and re-uploaded the `0.2.14` release with the fix
