### ISSUE TITLE
Can't import a dictionary

### ISSUE THREAD

**Issue by snam24** [mr-pennyworth/alfred-better-dictionaries#33]
On my Intel Mac, `.dict-import` does not load a list of dictionaries that can be imported. The related debug says:

> [11:24:10.835] Better Dictionaries[Script Filter] Queuing argument '(null)'

I tried `.dict-factory-reset` but it shows the following error (from the debug console) too:

> [11:25:00.205] Better Dictionaries[Keyword] Processing complete
> [11:25:00.210] Better Dictionaries[Keyword] Passing output '' to Run Script
> [11:25:01.897] ERROR: Better Dictionaries[Run Script] No matching processes belonging to you were found
/Users/myname/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/BA67CDCA-9D65-4831-95B8-45BC512D481A: line 12: ./python: Bad CPU type in executable

FWIW, my default shell is zsh.

**Comment by mr-pennyworth** [comment]
@snam24 thanks for pointing out that yours in an Intel mac.
Based on the error message, it looks like maybe you downloaded the workflow for Apple silicon?
Can you confirm which one you downloaded?
Here's the link to the correct one: [Better.Dictionaries.x86_64.alfredworkflow](https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/download/0.2.17/Better.Dictionaries.x86_64.alfredworkflow)

Or, is it the case that you have two macs, one Intel and one Apple Silicon?
If that's the case, unfortunately, the way the workflow is currently built, it seems like you'll always end up in a situation where it works on one and not on the other :(

**Comment by snam24** [comment]
I see, and yes, I use an Intel Mac and an Apple Silicon. I guess I have to use it on Apple Silicon only. Thanks!

**Comment by mr-pennyworth** [comment]
@snam24 one way to use the workflow on both your machines would be to rename the workflow ID on the Apple Silicon machine, and then download the workflow from github again on your Intel machine. Since (I'm assuming) you sync your workflow folder, you'll end up with having two workflows on both your machines, which is not ideal. However, this should not cause any usability problems (you can use the same keyword in both workflows, as only one of the two would produce results anyway)

Here's how you can rename the ID:
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/e518272d-9024-4dd4-8ffb-33ad205b44f6">

**Comment by snam24** [comment]
Hi @mr-pennyworth, sorry to bother and resurrect the closed issue, but I still have the same error. I changed the bundle id for the Intel Mac version of the workflow (x86_64) and also changed the keyword and placeholder title so as not to be confused with those of the arm version. (Changed bundle id for arm version as well)

When I tried `.dict-importINTEL`, the debug console still shows the following error and does not load the available dictionaries. Will you please look into this?
> [10:21:49.409] Better Dictionaries[Script Filter] Queuing argument '(null)'

**Comment by mr-pennyworth** [comment]
No worries about reopening @snam24!
I finally got access to an intel mac, so downloaded the workflow, and did `.dict-import`. It worked for me, however, I had to try three times, and also, more importantly, I had to wait for quite some time (like a minute or so).

So, something seems to make it slow, but it does seem to work.
Can you try and let me know?

**Comment by mr-pennyworth** [comment]
closing old issue
