### ISSUE TITLE
Got an error when I was importing "牛津英汉汉英字典" 

### ISSUE THREAD

**Issue by codiy1992** [mr-pennyworth/alfred-better-dictionaries#4]
Import dictionary with Chinese characters failed

**Comment by mr-pennyworth** [comment]
Can you provide the following info?

1. What is the error message?
2. What is in the logs?
3. Where is the dictionary located?
4. Does it successfully import other dictionaries?

**Comment by mr-pennyworth** [comment]
Closing the issue due to lack of debugging information
