### ISSUE TITLE
Feature Request: Option for bigger font size

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-better-dictionaries#6]
I love your workflow! Only thing I would change is to somehow increase the font size of the extra pane a bit. Or rather provide an option to do so. The font size right now is really small.

**Comment by mr-pennyworth** [comment]
Thanks @chrisgrieser for the feature request!
Fixed the font size in the latest release.
Sorry it is still not configurable, but now it is not tiny.
