### ISSUE TITLE
.dict_import script throws an error: `KeyError: 'CFBundleDisplayName'`

### ISSUE THREAD

**Issue by K021** [mr-pennyworth/alfred-better-dictionaries#9]
## Environment
- **BetterDict Release Version**: `v0.1.6`
- **macOS**: `Catalina`, `macOS 10.15.7` (19H2)
- **Alfred**: `v4.5`

## I faced problem, running `.dict-import` command
I have successfully set up preferences, and ran the `.dict-import` command in Alfred.

and I got this error:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/31090231/129178440-a6043993-390b-4e40-bf61-ede627325f73.png">

## So I checked the script works right or not
so I checked if the script works or not, in terminal, and it threw this error:

```
~/Dr/alfred/A/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6
> ./BetterDict.app/Contents/MacOS/BetterDict listUnimported "$alfred_workflow_data"
Traceback (most recent call last):
  File "/Users/jooeon/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Resources/__boot__.py", line 411, in <module>
    _run()
  File "/Users/jooeon/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/jooeon/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Resources/BetterDict.py", line 409, in <module>
    list_unimported_dicts(base_dir)
  File "/Users/jooeon/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Resources/BetterDict.py", line 385, in list_unimported_dicts
    dict_name = get_dict_name(info)
  File "/Users/jooeon/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Resources/BetterDict.py", line 243, in get_dict_name
    return info['CFBundleDisplayName']
KeyError: 'CFBundleDisplayName'
2021-08-12 18:59:01.149 BetterDict[1670:20844] BetterDict Error
```

but I think it has the key, `CFBundleDisplayName ` in the file:
`...../alfred/Alfred.alfredpreferences/workflows/user.workflow.B282BE19-0903-4B4B-8279-6014278C53A6/BetterDict.app/Contents/Info.plist`

<img width="856" alt="스크린샷 2021-08-12 오후 7 10 31" src="https://user-images.githubusercontent.com/31090231/129179664-96f864d8-2407-4b0a-9841-042040196349.png">

## I found the cause

and I realized that the error is not occurred in the file above, reading the source code, `BetterDict.py`. And I printed the `info` object:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/31090231/129182151-c85ce54e-bd03-462c-b02f-5f59dbb873ba.png">

And I found that there's some dictionary that doesn't has the key `'CFBundleDisplayName'` in it's `info.plist`

```python
{'CFBundleDevelopmentRegion': 'English',
 'CFBundleIdentifier': 'com.apple.accessibility.dictionary.TTY',
 'CFBundleInfoDictionaryVersion': '6.0',
 'CFBundleName': 'TTY Abbreviations',
 'CFBundleShortVersionString': '1.0',
 'DCSBuildToolVersion': 3,
 'DCSDictionaryCSS': 'DefaultStyle.css',
 'DCSDictionaryCopyright': 'Copyright © 2007-2019 Apple Inc. All Rights '
                           'Reserved.',
 'DCSDictionaryDefaultPrefs': {...},
 'DCSDictionaryFrontMatterReferenceID': 'front_back_matter',
 'DCSDictionaryManufacturerName': 'Apple Inc.',
 'DCSDictionaryPrefsHTML': 'TTYDictionary_prefs.html',
 'DCSDictionaryUseSystemAppearance': True,
 'DCSDictionaryXSL': 'TTYDictionary.xsl',
 'DCSElementXPath': {...},
 'IDXDictionaryIndexes': [...],
 'IDXDictionaryVersion': 3}
```

## I have changed the source code, but still has problems.

so I have changed the `get_dict_name` logic, like this:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/31090231/129183831-562b9c59-6296-40ca-9287-d5657d2aad72.png">

and executed `.dict-import` again.
this time, no error happened but no changes either.

and I found it just prints the result out:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/31090231/129184332-3d8291cd-5663-47dc-9ee7-7608842572ce.png">

is it right code?
Do you know how to solve this problem?
thanks!

**Comment by mr-pennyworth** [comment]
Thanks @K021 for the detailed report!
This should be fixed in https://github.com/mr-pennyworth/alfred-better-dictionaries/releases/tag/0.2.6
